# Generated by Django 5.1.7 on 2025-04-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('compassionate', 'Compassionate Leave'), ('study', 'Study Leave')], default='paid', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, help_text='Reason for the leave request (optional for some types, required for others).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('hr_approved', 'HR Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manager_approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('hr_approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if the request was rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['hr', 'admin', 'director']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hr_requests', to='employees.employee')),
                ('approved_by_manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['manager', 'admin', 'director']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manager_requests', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
