# Generated by Django 5.1.4 on 2024-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workassignments',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.CharField(choices=[('0', 'January'), ('1', 'February'), ('2', 'March'), ('3', 'April'), ('4', 'May'), ('5', 'June'), ('6', 'July'), ('7', 'August'), ('8', 'September'), ('9', 'October'), ('10', 'November'), ('11', 'December')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workassignments',
            name='Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
