# Generated by Django 5.1.4 on 2024-12-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='addharNo',
        ),
    ]
