# Generated by Django 5.1.7 on 2025-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Administrator'), ('hr', 'HR Staff'), ('director', 'Director')], default='employee', help_text='The role defines what permissions the employee has in the system', max_length=20),
        ),
    ]
