# Generated by Django 5.1.7 on 2025-04-21 08:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='paid_leave_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available paid leave days.', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available sick leave days.', max_digits=5),
        ),
    ]
